Repository normal-devs/klicker-knight, pull requests merged in 2022-02, with the labels that each got.

#32 Adding the fire room design!
  docs/rooms/fireRoom.md
Labels: room documentation

#41 Skip the e2e tests so we can add new rooms without issue
  tests/e2e/klickerKnight.test.ts
Labels: size: smol

#36 Fix eslint-ignore placement in compiled file
  scripts/compileRoomTypesTuple.ts
  src/utils/types/roomTypesTuple.ts
Labels: size: smol

#37 Verbosify transition test output
  tests/src/roomHandlers/exampleRoom1Handler.test.ts
  tests/src/roomHandlers/exampleRoom2Handler.test.ts
  tests/src/roomHandlers/exampleRoom3Handler.test.ts
  tests/testHelpers/buildStateTransitionHelpers.ts
Labels: enhancement, size: small

#42 Implement the roomception room
  docs/rooms/roomceptionRoom.md
  src/roomHandlers/roomceptionRoomHandler.ts
  src/utils/roomUtil.ts
  src/utils/types/gameState.d.ts
  src/utils/types/gameState.schema.json
  src/utils/types/roomTypesTuple.ts
  tests/src/roomHandlers/roomceptionRoomHandler.test.ts
  tests/testHelpers/buildStateTransitionHelpers.ts
Labels: size: small, room documentation, room implementation
